"""add recovery_attempts

Revision ID: f2eca2bcd3f4
Revises: d3ffaed52260
Create Date: 2025-10-07 22:47:14.770684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f2eca2bcd3f4'
down_revision: Union[str, Sequence[str], None] = 'd3ffaed52260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_ref'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_failure_events_transaction_id'), table_name='failure_events')
    op.drop_table('failure_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('gateway', sa.VARCHAR(length=32), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=128), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_events_transaction_id'), 'failure_events', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_ref', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_ref'), 'transactions', ['transaction_ref'], unique=1)
    # ### end Alembic commands ###
