"""ensure core tables

Revision ID: fceed77511ca
Revises: 91315643636f
Create Date: 2025-10-07 20:12:45.558133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fceed77511ca'
down_revision: Union[str, Sequence[str], None] = '91315643636f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attempts_order'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('idx_events_order'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('order_id', sa.TEXT(), nullable=False),
    sa.Column('attempt_id', sa.TEXT(), nullable=True),
    sa.Column('customer_id', sa.TEXT(), nullable=True),
    sa.Column('event_type', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('failure_code', sa.TEXT(), nullable=True),
    sa.Column('failure_message', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'INR'"), nullable=True),
    sa.Column('raw_json', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_events_order'), 'events', ['order_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('order_id', sa.TEXT(), nullable=False),
    sa.Column('attempt_from_event', sa.TEXT(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('strategy', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_attempts_order'), 'attempts', ['order_id'], unique=False)
    # ### end Alembic commands ###
