apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinko-backend
  labels:
    app: tinko-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tinko-backend
  template:
    metadata:
      labels:
        app: tinko-backend
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/stealth-recovery-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: tinko-backend-config
            - secretRef:
                name: tinko-backend-secret
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: data
          emptyDir: {}
